ci:
  autofix_commit_msg: "格式化代码"
  autofix_prs: true
  autoupdate_branch: main

repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.9.0'  # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
